document:
  page_size: A4
  margins:
    top: 2cm
    bottom: 2cm
    left: 2cm
    right: 2cm

fonts:
  body: "Roboto"
  heading: "Roboto Slab"
  code: "Fira Code"
  base_size: 11pt
  line_height: 1.5

styles:
  h1:
    size: 24pt
    weight: bold
    color: "#333333"
  h2:
    size: 18pt
    weight: bold
    color: "#444444"
  h3:
    size: 14pt
    weight: bold
    color: "#555555"
  h4:
    size: 12pt
    weight: bold
    color: "#666666"
  h5:
    size: 11pt
    weight: bold
    color: "#666666"
  h6:
    size: 10pt
    weight: bold
    color: "#666666"
